version: '3'
services:
  prominent-api-docker:
    image: prominent:1
    container_name: prominent_api
    build: .
    ports:
      - "8081:8080"
    hostname: localhost
    restart: always
    depends_on:
      - mypostgres1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres1:5432/prominent
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
  mypostgres1:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root@123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=prominent