version: '2'

services:
  db:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prominent
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data